#!/bin/sh

CWD=$(CDPATH='' cd -- "$(dirname -- "$0")" && pwd) || exit 1

core="${CWD}/core.txt"
if ! [ -f "$core" ]; then
    echo "No core requirement file: $core" >&2
    exit 1
fi

ocaml="${CWD}/ocaml-std"
if ! [ -x "$ocaml" ]; then
    echo "No OCaml compiler helper: $ocaml" >&2
    exit 1
fi

exec "$ocaml" -r "$core" "$@"
